services:
  backend:
    build:
      context: ./django/
      dockerfile: ./Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    volumes:
      - ./django/:/django/
    ports:
      - 8000:8000
    env_file:
      - ./.env
  db:
    image: postgres:13.0-alpine
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  frontend:
    build:
      context: ./vue/
      dockerfile: ./Dockerfile
    command: yarn run dev
    depends_on:
      - backend
    volumes:
      - ./vue/:/vue/
    ports:
      - 3000:3000
    env_file: ./.env

volumes:
  postgres_data:
