# Generated by Django 4.0.3 on 2022-03-06 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0002_alter_receiptitem_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptitem',
            name='scanned_at',
        ),
    ]
